language: ruby
rvm:
  - 2.3.1

# Use PostgreSQL as database
services:
  - postgresql

before_script:
  - psql -c 'create database community_democracy_test;' -U postgres

script: xvfb-run bundle exec rspec spec

# whitelist
branches:
  only:
    - master
    - development

env:
  - MAILJET_API_KEY: spoof
  - MAILJET_SECRET_KEY: spoof
